version: '3.3'

volumes:
  pg_data:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  cat_exhibition:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
